name: Performance Issue
description: Issues related to performance
title: "performance: "
type: performance
labels:
  - performance
assignees:
  - Alex200207
  - Cris281
projects:
  - Vital-IA
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Include the details of the performance issue
    validations:
      required: false
  - type: input
    id: filename
    attributes:
      label: Filename / Path
      description: Add the file or path where the issue is located
    validations:
      required: false
